services:

#    souv_security.event_listener.kernel_event_listener:
#      class: Souv\SecurityBundle\EventListener\KernelEventListener
#      arguments: ["@service_container", "@security.token_storage" ]
#      tags:
#        - { name: kernel.event_listener, event: kernel.controller, method: addUserOnKernelController, priority: 100 }
#        - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
#
#    souv_security.event_listener.kernel_exception_event_listener:
#      class: Souv\SecurityBundle\EventListener\KernelExceptionEventListener
#      arguments: ["@service_container" ]
#      tags:
#        - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100 }

    souv_core.event_listener.kernel_event_listener:
      class: AppBundle\EventListener\KernelEventListener
      arguments: [ "@service_container" ]
      tags:
        - { name: kernel.event_listener, event: kernel.controller, method: initController, priority: 0 }
